version: '3.0'

services:
  redis:
    image: redis:alpine

  app:
    image: clojure:alpine
    working_dir: '/app'
    ports:
      - '3000:3000'
      - '7888:7888'
    volumes:
      - '.:/app'
    command: 'lein ring server'
    tty: true
    depends_on:
      - redis
